<?php

namespace backend\controllers;

use common\models\Goods;
use common\models\Category;
use common\models\Brand;
use yii;
use common\helpers\Tools;
use common\models\UploadForm;
use yii\data\Pagination;
use common\models\GoodsGallery;
use Qiniu\Auth;
use Qiniu\Storage\UploadManager;
use yii\helpers\ArrayHelper;
use yii\web\Response;
use yii\web\UploadedFile;


class GoodsController extends \yii\web\Controller
{
    public function beforeAction($action)
    {
        $noCsrfActions = ['gallery','xxx'];
        if(in_array($action->id,$noCsrfActions))
        {
            $action->controller->enableCsrfValidation = false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionCreate()
    {
        $model = new Goods();
        $upload = new UploadForm();
        if(Yii::$app->request->isPost)
        {
            if($model->createGoods())
            {
                Tools::success('商品添加成功',['goods/index']);
            }
            else
            {
                Tools::error('商品添加失败');
            }
        }
        // 下拉菜单
        $catList = (new Category())->dropDownList();
        $brandList = (new Brand())->dropDownList();
        return $this->render('create',['model'=>$model,'upload'=>$upload,'catList'=>$catList,'brandList'=>$brandList]);
    }

    public function actionDelete()
    {
        return $this->render('delete');
    }

    public function actionIndex()
    {
        $sql= Goods::find();
        $catList = (new Category())->dropDownList();
        $brandList = (new Brand())->dropDownList();
        $PageSize=yii::$app->params['pageSize'];

        if(Yii::$app->request->isGet){
            //            echo '1';die;
            $post =yii::$app->request->get();

            $sql=(new Goods())->readWhere($sql);
            if (!empty($post['goodsList_id']))
            {
                $sql=(new Goods())->aa($sql,$post['goodsList_id']);
            }
        }

        $pagination = new Pagination([
            'defaultPageSize' => $PageSize,
            'totalCount' => $sql->count(),
        ]);
        $countries = $sql
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();
        return $this->render('index',['pagination' => $pagination,'countries'=>$countries,'catList'=>$catList,'brandList'=>$brandList]);
    }

    public function actionUpdate()
    {
        return $this->render('update');
    }

    /**
     * 上传图片至七牛云
     */
    public function actionGallery($gid='',$gname='')
    {
        if(Yii::$app->request->isPost && Yii::$app->request->isAjax)
        {
            // 上传至七牛云
            $upForm = new UploadForm();
            $upForm->imageFile = UploadedFile::getInstance($upForm,'imageFile');
            $result = $upForm->uploadToQiNiu();
            if($result['code'] == 0)
            {
                // 入库
                $gid = Yii::$app->request->post('gid');
                $data = ['goods_id'=>$gid,'original_img'=>$result['data']['src']];
                if(!(new GoodsGallery())->createGallery($data))
                {
                    $result['code'] = 200;
                    $result['msg'] = '图片入库失败.';
                }
            }
            Yii::$app->response->format = Response::FORMAT_JSON;
            // 响应 JSON
            return $result;
        }
        // 该商品下的图片
        $galleries = (new GoodsGallery())->getGalleries($gid);
        return $this->render('gallery',['gname'=>$gname,'gid'=>$gid,'galleries'=>$galleries]);
    }


}
